# Generated by Django 4.1.3 on 2022-12-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoriyaproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriyaproduct',
            name='categoriya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoriya'),
        ),
    ]
