# Generated by Django 4.1.3 on 2022-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categoriyaproduct_categoriya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriya',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CategoriyaProduct',
        ),
    ]
