# Generated by Django 4.1.3 on 2022-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_categoriya_name_delete_categoriyaproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriyaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='categoriya',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
